post_install() {
    USER_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
    
    # Service addon
    mkdir -p "$USER_HOME/.kodi/addons/service.xbmc.tts"
    cp -r /usr/share/kodi/addons/service.xbmc.tts/* "$USER_HOME/.kodi/addons/service.xbmc.tts/"
    
    # Keyboard mappings
    mkdir -p "$USER_HOME/.kodi/userdata/keymaps"
    cp /etc/kodi/userdata/keymaps/service.xbmc.tts.keyboard.xml "$USER_HOME/.kodi/userdata/keymaps/"
    
    # Activation flag
    mkdir -p "$USER_HOME/.kodi/userdata/addon_data/service.xbmc.tts"
    cp /etc/kodi/userdata/addon_data/service.xbmc.tts/ENABLED "$USER_HOME/.kodi/userdata/addon_data/service.xbmc.tts/"
    
    # Fix permissions
    chown -R "$SUDO_USER":"$SUDO_USER" "$USER_HOME/.kodi"
}

post_upgrade() {
    post_install
}

