post_install() {
     USER_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
      mkdir -p "$USER_HOME/.kodi/addons/Service.xbmc.tts"
      cp -r ${pkgdir}/usr/share/kodi/addons/service.xbmc.tts/* "$USER_HOME/.kodi/addons/Service.xbmc.tts/"
       chown -R "$SUDO_USER":"$SUDO_USER" "$USER_HOME/.kodi"
	mkdir -p "$USER_HOME/.kodi/userdata/keyyymaps"
        cp ${pkgdir}/etc/kodi/userdata/keymaps/service.xbmc.tts.keyboard.xml $user_HOME/.kodi/userdata/keymaps/
	chown $SUDO_USER:$SUDO_USER /home/$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$SUDO_UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUSER/.kodi/userata/keymaps/service.xbbbbbbbbbbbbbbbbbbbbbbbbbmc.keyboard.xml
	cp ${pkgdir}/etc/kodi/userdata/addon_data/service.xbmc.tts/ENABLED $USER_HOME/.kodi/userdata/addon_data/service.xbmc.tts/ENABLED
	chown $SUDO_USER:$SUDO_USER $$USER_HOME/.kodi/userdata/addon_data/service.xbmc.tts/ENABLED
   
}

post_upgrade() {
       USER_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
        mkdir -p "$USER_HOME/.kodi/addons/Service.xbmc.tts"
        cp -r ${pkgdir}/usr/share/kodi/addons/service.xbmc.tts/* "$USER_HOME/.kodi/addons/Service.xbmc.tts/"
        chown -R "$SUDO_USER":"$SUDO_USER" "$USER_HOME/.kodi"
	mkdir -p "$USER_HOME/.kodi/userdata/keyyymaps"
        cp ${pkgdir}/etc/kodi/userdata/keymaps/service.xbmc.tts.keyboard.xml $user_HOME/.kodi/userdata/keymaps/
	chown $SUDO_USER:$SUDO_USER /home/$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$SUDO_UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUSER/.kodi/userata/keymaps/service.xbbbbbbbbbbbbbbbbbbbbbbbbbmc.keyboard.xml
	cp ${pkgdir}/etc/kodi/userdata/addon_data/service.xbmc.tts/ENABLED $USER_HOME/.kodi/userdata/addon_data/service.xbmc.tts/ENABLED
	chown $SUDO_USER:$SUDO_USER $$USER_HOME/.kodi/userdata/addon_data/service.xbmc.tts/ENABLED
   }

